### ISSUE TITLE
[BUG] Recently updated dependency Elastic.Transport 0.4.18 break the use of ElasticsearchSinkOptions

### ISSUE THREAD

**Issue by GuillaumeBau** [elastic/ecs-dotnet#363]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**: Elastic.Serilog.Sinks 

**ECS schema version (e.g. 1.4.0)**: 8.6.1

**ECS .NET assembly version (e.g. 1.4.2)**: 8.6.1

**Elasticsearch version (if applicable)**:

**.NET framework / OS**: .NET 6

**Description of the problem, including expected versus actual behavior**:
The new Elastic.Transport version introduce the ITransport Interface (https://github.com/elastic/elasticsearch-net/pull/8061)
Doing "new ElasticsearchSinkOptions(ITransport)" cause the error CS7069	Reference to type 'HttpTransport' claims it is defined in 'Elastic.Transport', but it could not be found

![image](https://github.com/elastic/ecs-dotnet/assets/4007634/dc21c4bf-1922-4ed8-80f2-2595e723f2ae)

Works with Elastic.Clients.Elasticsearch 8.12.0, the error was introduce when updating to 8.12.1

**Comment by cbusjay** [comment]
I have this same issue.

**Comment by Mpdreamz** [comment]
Thank you for raising this @GuillaumeBau we're addressing this here first: 

https://github.com/elastic/elastic-ingest-dotnet/pull/47

And will shortly after update all references for the ecs-dotnet libraries as well.

**Comment by Mpdreamz** [comment]
This has been addressed here: https://github.com/elastic/ecs-dotnet/pull/364
